/* ═══════════════════════════════════════════
   Übersetzungen DE / EN
   ═══════════════════════════════════════════ */

const LANG = {
  de: {
    searchPlaceholder:  'Aktie suchen – z.B. AAPL, TSLA, SAP …',
    btnAnalyze:         'Analysieren',
    demoBanner:         '⚡ Demo-Modus – Beispieldaten werden angezeigt.',
    demoSetup:          'API-Keys einrichten →',
    chartTitle:         'Kursverlauf & Prognose',
    chartLine:          'Linie',
    chartCandle:        'Kerzen',
    indicators:         'Technische Indikatoren',
    forecastTitle:      'KI-Prognose',
    recommendation:     'Empfehlung',
    priceTarget:        'Kursziel',
    confidence:         'Konfidenz',
    factorsTitle:       'Prognosefaktoren',
    fac_reg:            '📐 Lineare Regression',
    fac_trend:          '📈 Technischer Trend',
    fac_mom:            '⚡ Momentum (RSI/MACD)',
    fac_sent:           '📰 Nachrichten-Sentiment',
    watchlistTitle:     'Watchlist',
    watchlistEmpty:     'Noch keine Aktien gespeichert.',
    watchlistAddCurrent:'+ Zur Watchlist',
    watchlistInList:    '✓ In Watchlist',
    watchlistRemove:    'Entfernen',
    newsTitle:          'Aktuelle Nachrichten',
    disclaimer:         '⚠️ Prognosen dienen nur zur Information und stellen keine Anlageberatung dar.',
    rec_buy:            'KAUFEN',
    rec_hold:           'HALTEN',
    rec_sell:           'VERKAUFEN',
    updatedAt:          'Aktualisiert:',
    marketTitle:        'Märkte',
    period_1T:          '1T',
    period_1W:          '1W',
    period_1M:          '1M',
    period_3M:          '3M',
    period_6M:          '6M',
    period_1J:          '1J',
    fc_7:               '7T',
    fc_14:              '14T',
    fc_30:              '30T',
    rsi_overbought:     'Überkauft – Vorsicht',
    rsi_oversold:       'Überverkauft – Chance',
    rsi_neutral:        'Neutral',
    macd_bull:          'Bullish – Signal überschritten',
    macd_bear:          'Bearish – unter Signal-Linie',
    above_sma:          'Kurs über SMA ▲',
    below_sma:          'Kurs unter SMA ▼',
    bb_upper:           'Oberes Band – überkauft',
    bb_lower:           'Unteres Band – überverkauft',
    bb_mid:             'Mittleres Band',
    vol_low:            'Niedrig',
    vol_mod:            'Moderat',
    vol_high:           'Hoch',
    settings_title:     'Einstellungen',
    settings_proxy:     'Cloudflare Proxy-URL',
    settings_proxy_sub: 'Alle Besucher erhalten Echtzeit-Daten automatisch',
    settings_or:        'oder direkte API-Keys (nur für Sie persönlich)',
    settings_save:      'Speichern & neu laden',
    settings_clear:     'Alles löschen',
    loading:            'Daten werden geladen …',
    intraday_na:        'Intraday-Daten nicht verfügbar',
    leg_price:          'Kurs',
    leg_sma20:          'SMA 20',
    leg_sma50:          'SMA 50',
    leg_forecast:       'Prognose',
    sent_positive:      'Positiv',
    sent_negative:      'Negativ',
    sent_neutral:       'Neutral',
  },
  en: {
    searchPlaceholder:  'Search stock – e.g. AAPL, TSLA, SAP …',
    btnAnalyze:         'Analyze',
    demoBanner:         '⚡ Demo mode – sample data is shown.',
    demoSetup:          'Set up API keys →',
    chartTitle:         'Price Chart & Forecast',
    chartLine:          'Line',
    chartCandle:        'Candle',
    indicators:         'Technical Indicators',
    forecastTitle:      'AI Forecast',
    recommendation:     'Recommendation',
    priceTarget:        'Price Target',
    confidence:         'Confidence',
    factorsTitle:       'Forecast Factors',
    fac_reg:            '📐 Linear Regression',
    fac_trend:          '📈 Technical Trend',
    fac_mom:            '⚡ Momentum (RSI/MACD)',
    fac_sent:           '📰 News Sentiment',
    watchlistTitle:     'Watchlist',
    watchlistEmpty:     'No stocks saved yet.',
    watchlistAddCurrent:'+ Add to Watchlist',
    watchlistInList:    '✓ In Watchlist',
    watchlistRemove:    'Remove',
    newsTitle:          'Latest News',
    disclaimer:         '⚠️ Forecasts are for informational purposes only and do not constitute investment advice.',
    rec_buy:            'BUY',
    rec_hold:           'HOLD',
    rec_sell:           'SELL',
    updatedAt:          'Updated:',
    marketTitle:        'Markets',
    period_1T:          '1D',
    period_1W:          '1W',
    period_1M:          '1M',
    period_3M:          '3M',
    period_6M:          '6M',
    period_1J:          '1Y',
    fc_7:               '7D',
    fc_14:              '14D',
    fc_30:              '30D',
    rsi_overbought:     'Overbought – Caution',
    rsi_oversold:       'Oversold – Opportunity',
    rsi_neutral:        'Neutral',
    macd_bull:          'Bullish – Above signal line',
    macd_bear:          'Bearish – Below signal line',
    above_sma:          'Price above SMA ▲',
    below_sma:          'Price below SMA ▼',
    bb_upper:           'Upper band – overbought',
    bb_lower:           'Lower band – oversold',
    bb_mid:             'Middle band',
    vol_low:            'Low',
    vol_mod:            'Moderate',
    vol_high:           'High',
    settings_title:     'Settings',
    settings_proxy:     'Cloudflare Proxy URL',
    settings_proxy_sub: 'All visitors get real-time data automatically',
    settings_or:        'or direct API keys (for your browser only)',
    settings_save:      'Save & reload',
    settings_clear:     'Clear all',
    loading:            'Loading data …',
    intraday_na:        'Intraday data not available',
    leg_price:          'Price',
    leg_sma20:          'SMA 20',
    leg_sma50:          'SMA 50',
    leg_forecast:       'Forecast',
    sent_positive:      'Positive',
    sent_negative:      'Negative',
    sent_neutral:       'Neutral',
  }
};
